<?php
include 'head.php'
?>
<b> CHECKLIST </b>
<ul>
 <li> SALTED HASH PASSWORDS <b> done </b> 
 <li><i> REVIEWS: </i>
 	<li> TABLE <b> done </b>
 	<li> QUERYING 
 	<li> INSERTS IN ITEM PAGE 
 	<li> REMOVE REVIEW SECTION WHEN LOGGED OUT
 	<li> SEARCH PAGE REVIEWS
 	<li> PREVENT USER FROM SUBMITTING TWO REVIEWS
 <li> SORTING BY REVIEWS
 <li> BETTER MAP INTEGRATION - ITEM AND SEARCH PAGES.
 <li> MOVE THINGS TO THEIR OWN PHP FILES - PARTICULARLY DATABASE AND PROCESSING THINGS.
 <li> IMPROVE CSS - MOVE PAGE SPECIFIC THINGS TO SEPARATE CSS FILES. COMMENT CSS. 
 <li> REMOVE THIS PAGE.
 <li> TEST ACCOUNT - TestAccount (username), password1 
 <li> !ERROR MESSAGE ON ACCOUNT CREATION WITH ALREADY IN-USE USERNAME.
 <li> item page has double content divs
 		</ul>